# Generated by Django 2.2.10 on 2021-04-10 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_id', models.IntegerField()),
                ('text', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('checked', models.BooleanField(blank=True, default=None, null=True)),
                ('poll_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Poll')),
            ],
        ),
        migrations.CreateModel(
            name='TypeAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('1', 'TextQuestion'), ('2', 'OneQuestion'), ('3', 'ManyQuestion')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_question', models.CharField(default='Question', max_length=100, null=True)),
                ('text_q', models.TextField(max_length=1000, verbose_name='Вопрос')),
                ('text', models.TextField(default='', verbose_name='Текстовый ответ')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Poll')),
            ],
        ),
        migrations.CreateModel(
            name='OneQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_question', models.CharField(default='Question', max_length=100, null=True)),
                ('text_q', models.TextField(max_length=1000, verbose_name='Вопрос')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Poll')),
                ('var_answer', models.ManyToManyField(to='polls.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='ManyQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_question', models.CharField(default='Question', max_length=100, null=True)),
                ('text_q', models.TextField(max_length=1000, verbose_name='Вопрос')),
                ('many_answer', models.ManyToManyField(to='polls.Answer')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Poll')),
            ],
        ),
        migrations.AddIndex(
            model_name='textquestion',
            index=models.Index(fields=['poll'], name='polls_textq_poll_id_8a16f2_idx'),
        ),
        migrations.AddIndex(
            model_name='onequestion',
            index=models.Index(fields=['poll'], name='polls_onequ_poll_id_8280d7_idx'),
        ),
        migrations.AddIndex(
            model_name='manyquestion',
            index=models.Index(fields=['poll'], name='polls_manyq_poll_id_7cdfda_idx'),
        ),
    ]
