# Generated by Django 2.2.10 on 2021-04-07 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='poll',
            name='date_end',
            field=models.DateTimeField(auto_now=True, verbose_name='Конец опроса'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='date_start',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Старт опроса'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_q', models.TextField(max_length=1000, verbose_name='Вопрос')),
                ('type_q', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.TypeAnswer')),
            ],
        ),
        migrations.AddField(
            model_name='poll',
            name='select_question',
            field=models.ManyToManyField(to='polls.Question'),
        ),
    ]
