# Generated by Django 2.2.10 on 2021-04-07 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210407_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['-poll_id']},
        ),
        migrations.AddField(
            model_name='typeanswer',
            name='title',
            field=models.CharField(choices=[('TYPE_1', 'type_1'), ('TYPE_2', 'type_2'), ('TYPE_3', 'type_3')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='type_q',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.TypeAnswer'),
        ),
    ]
