# Generated by Django 2.2.10 on 2021-04-10 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210410_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_question', models.CharField(default='Question', max_length=100, null=True)),
                ('text_q', models.TextField(max_length=1000, verbose_name='Вопрос')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Poll')),
            ],
        ),
        migrations.RemoveField(
            model_name='onequestion',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='onequestion',
            name='var_answer',
        ),
        migrations.RemoveField(
            model_name='textquestion',
            name='poll',
        ),
        migrations.AlterField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
        migrations.DeleteModel(
            name='ManyQuestion',
        ),
        migrations.DeleteModel(
            name='OneQuestion',
        ),
        migrations.DeleteModel(
            name='TextQuestion',
        ),
    ]
