# Generated by Django 2.2.10 on 2021-04-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210410_1147'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TypeAnswer',
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='type_question',
            field=models.CharField(choices=[('1', 'TextQuestion'), ('2', 'OneQuestion'), ('3', 'ManyQuestion')], default='Question', max_length=100, null=True),
        ),
    ]
