# Generated by Django 2.2.10 on 2021-04-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210407_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='select_question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='type_q',
        ),
        migrations.AddField(
            model_name='poll',
            name='count_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='type_question',
            field=models.CharField(default='Question', max_length=100, null=True),
        ),
    ]
