# Generated by Django 2.2.10 on 2021-04-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210407_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('poll_id', models.IntegerField()),
                ('question_id', models.IntegerField()),
                ('text', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('checked', models.BooleanField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_question', models.CharField(default='Question', max_length=100, null=True)),
                ('text_q', models.TextField(max_length=1000, verbose_name='Вопрос')),
                ('text', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='count_answers',
        ),
    ]
