# Generated by Django 2.2.10 on 2021-04-07 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210408_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='textquestion',
            name='poll',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='polls.Poll'),
        ),
        migrations.AlterField(
            model_name='textquestion',
            name='text',
            field=models.TextField(default='', verbose_name='Текстовый ответ'),
        ),
        migrations.AlterField(
            model_name='typeanswer',
            name='title',
            field=models.CharField(choices=[('1', 'TextQuestion'), ('2', 'OneQuestion'), ('3', 'ManyQuestion')], max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='textquestion',
            index=models.Index(fields=['poll'], name='polls_textq_poll_id_8a16f2_idx'),
        ),
    ]
