# Generated by Django 2.2.10 on 2021-04-07 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210408_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_question', models.CharField(default='Question', max_length=100, null=True)),
                ('text_q', models.TextField(max_length=1000, verbose_name='Вопрос')),
                ('poll', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='polls.Poll')),
                ('var_answer', models.ManyToManyField(to='polls.Answer')),
            ],
        ),
        migrations.AddIndex(
            model_name='onequestion',
            index=models.Index(fields=['poll'], name='polls_onequ_poll_id_8280d7_idx'),
        ),
    ]
