# Generated by Django 2.2.10 on 2021-04-07 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20210408_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManyQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_question', models.CharField(default='Question', max_length=100, null=True)),
                ('text_q', models.TextField(max_length=1000, verbose_name='Вопрос')),
                ('many_answer', models.ManyToManyField(to='polls.Answer')),
                ('poll', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='polls.Poll')),
            ],
        ),
        migrations.AddIndex(
            model_name='manyquestion',
            index=models.Index(fields=['poll'], name='polls_manyq_poll_id_7cdfda_idx'),
        ),
    ]
